-- 用户表
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(50),
    avatar VARCHAR(500),
    total_games INT DEFAULT 0,
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    draws INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 对局记录表
CREATE TABLE IF NOT EXISTS game_records (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    game_mode VARCHAR(20) NOT NULL COMMENT 'AI/LOCAL',
    difficulty VARCHAR(20) COMMENT 'EASY/MEDIUM/HARD',
    result VARCHAR(10) NOT NULL COMMENT 'WIN/LOSE/DRAW',
    player_color VARCHAR(10) NOT NULL COMMENT 'BLACK/WHITE',
    moves TEXT COMMENT 'JSON格式落子记录',
    duration INT DEFAULT 0 COMMENT '对局时长(秒)',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
